wallpaper {
        monitor = DP-1
        path = ~/.config/dotfiles/files/wallpapers/tree.jpg
        
}
wallpaper {
        monitor = HDMI-A-2
        path = ~/.config/dotfiles/files/wallpapers/tree.jpg
        
}
