- name: Ensure ~/.config exists
  file:
    path: "{{config_dir}}"
    state: directory

- name: Link config files and directories to {{ config_dir }}
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ config_dir }}/{{ item }}"
    state: link
  loop:
    - direnv
    - fish
    - git
    - lazygit
    - npm
    - nvim
    - starship.toml
    - tmux
    - wezterm
    - .zshenv
    - zsh
    - zellij
    - ghostty

- name: Link dotfiles to home directory
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ ansible_user_dir }}/{{ item }}"
    state: link
  loop:
    - .zshenv
