- name: Ensure fish is installed
  command: which fish
  register: fish_check
  changed_when: false
  failed_when: fish_check.rc != 0

- name: Set fish path from which if not provided
  set_fact:
    fish_shell_path: "{{ fish_check.stdout }}"
  when: fish_shell_path is not defined or fish_shell_path == ''

- name: Ensure fish is in /etc/shells
  lineinfile:
    path: /etc/shells
    line: "{{ fish_shell_path }}"
    state: present
  become: true

- name: Change default shell to fish
  user:
    name: "{{ ansible_user_id }}"
    shell: "{{ fish_shell_path }}"
  become: true

- name: Set sudo via Touch ID in sudo_local
  become: true
  lineinfile:
    path: /etc/pam.d/sudo_local
    line: "auth       sufficient     pam_tid.so"
    state: present
  tags:
    - touchid
