#!/usr/bin/env bash

function is_installed {
command -v "$1" >/dev/null 2>&1
}

system_type=$(uname -s)

if [[ "$system_type" == "Darwin" ]]; then
  
  if ! is_installed brew; then
    echo "Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi
  
  if ! is_installed ansible >/dev/null 2>&1; then
    echo "Installing Ansible..."
    brew install ansible
  fi

  

  # brewfile="bootstrap/homebrew/Brewfile.$system_name"
  # if [[ -f "$brewfile" ]]; then
  #   echo "Updating Homebrew from $brewfile"
  #   brew bundle --file="$brewfile"
  # else
  #   echo "No Brewfile found at $brewfile"
  # fi

fi

HOSTS="./hosts.ini"
PLAYBOOK="./macbook.yml"

ansible-playbook -i "$HOSTS" "$PLAYBOOK" --ask-become-pass -l macbook
