#!/bin/zsh

system_type=$(uname -s)

if [[ "$system_type" = "Darwin" ]]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi

  if [[ -v HOMEBREW_BUNDLE_FILE ]]; then
    echo "Updating homebrew from $HOMEBREW_BUNDLE_FILE"
    brew bundle --file $HOMEBREW_BUNDLE_FILE
  fi

fi
