gui:
  theme:
    activeBorderColor:
      - "#d8a657"
      - bold

    inactiveBorderColor:
      - "#7c6f64"

    searchingActiveBorderColor:
      - "#d3869b"
      - bold

    optionsTextColor:
      - "##7daea3"

    selectedLineBgColor:
      - "#504945"

    inactiveViewSelectedLineBgColor:
      - "#3c3836"
      - bold

    cherryPickedCommitFgColor:
      - "#504945"

    cherryPickedCommitBgColor:
      - "#d3869b"

    markedBaseCommitFgColor:
      - "#7daea3"

    markedBaseCommitBgColor:
      - "#d8a657"

    unstagedChangesColor:
      - "#ea6962"

    defaultFgColor:
      - "#d4be98"

os:
  editPreset: nvim-remote
