ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS=+(vi-forward-word)

# ZSH substring searching
HISTORY_SUBSTRING_SEARCH_ENSURE_UNIQUE=1
HISTORY_SUBSTRING_SEARCH_PREFIXED=1
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND='bg=#1e1e2e,fg=yellow,bold'
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_NOT_FOUND='bg=#1e1e2e,fg=magenta,bold'

unsetopt beep
