# A few variables are set in .zshenv also

export BUNDLE_USER_CACHE="$XDG_CACHE_HOME/bundle"
export BUNDLE_USER_CONFIG="$XDG_CONFIG_HOME/bundle"
export BUNDLE_USER_PLUGIN="$XDG_DATA_HOME/bundle"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export CONDARC="$XDG_CONFIG_HOME/conda/condarc"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export DOTFILES="/Users/hcq343/.dotfiles"
export JULIA_DEPOT_PATH="$XDG_DATA_HOME/julia:$JULIA_DEPOT_PATH"
export LESSHISTFILE="$XDG_STATE_HOME/less/history"
export NPM_CONFIG_CACHE="$XDG_CACHE_HOME/npm"
export NPM_CONFIG_INIT_MODULE="$XDG_CONFIG_HOME/npm/config/npm-init.js"
export NPM_CONFIG_TMP="$XDG_RUNTIME_DIR/npm"
export PYTHON_HISTORY="$XDG_STATE_HOME/python_history"
export R_HISTFILE="$XDG_STATE_HOME/R/history"
export EDITOR="nvim"
export STOW_DIR="$DOTFILES"
export HOMEBREW_BUNDLE_FILE="$DOTFILES/hosts/mac/$HOST/Brewfile"
export ZIM_HOME="$XDG_DATA_HOME/zim"
export HISTFILE="$XDG_STATE_HOME/zsh/history"
export LSCOLORS="Gxfxcxdxbxegedabagacad"
export MAMBA_EXE='/opt/homebrew/bin/micromamba'
export MAMBA_ROOT_PREFIX="$XDG_DATA_HOME/micromamba"
