add_newline = false
palette = "gruvbox_material_dark"


[cmd_duration]
disabled = true

[conda]
format = "[$symbol$environment]($style) "

[directory]
style = "bold color_blue"

[git_branch]
format = "on [$symbol$branch(:$remote_branch)]($style) "
style = "bold color_orange"

[git_status]
style = "bold color_orange"

[palettes.gruvbox_material_dark]
color_fg0 = '#d4be98'
color_bg1 = '#282828'
color_bg3 = '#3c3836'
color_blue = '#7daea3'
color_aqua = '#89b482'
color_green = '#a9b665'
color_orange = '#e78a4e'
color_purple = '#d3869b'
color_red = '#ea6962'
color_yellow = '#d8a657'


[python]
symbol = " "
style = "bold color_yellow"
format = '[$symbol( $version) ]($style) '

[rust]
format = "[$symbol ($version)]($style) "
style = "bold color_orange"
symbol = " "
