# ZDOTDIR is set in .zshenv

export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_RUNTIME_DIR="$HOME/.xdg-runtime"
export XDG_STATE_HOME="$HOME/.local/state"

export CARGO_HOME="$XDG_DATA_HOME/cargo"

export BUNDLE_USER_CACHE="$XDG_CACHE_HOME/bundle"
export BUNDLE_USER_CONFIG="$XDG_CONFIG_HOME/bundle"
export BUNDLE_USER_PLUGIN="$XDG_DATA_HOME/bundle"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export CONDARC="$XDG_CONFIG_HOME/conda/condarc"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export DOTFILES="$HOME/.dotfiles"
export JULIA_DEPOT_PATH="$XDG_DATA_HOME/julia:$JULIA_DEPOT_PATH"
export LESSHISTFILE="$XDG_STATE_HOME/less/history"
export NPM_CONFIG_CACHE="$XDG_CACHE_HOME/npm"
export NPM_CONFIG_INIT_MODULE="$XDG_CONFIG_HOME/npm/config/npm-init.js"
export NPM_CONFIG_TMP="$XDG_RUNTIME_DIR/npm"
export PYTHON_HISTORY="$XDG_STATE_HOME/python_history"
export R_HISTFILE="$XDG_STATE_HOME/R/history"
export EDITOR="nvim"
export STOW_DIR="$DOTFILES/stow"
export HOMEBREW_BUNDLE_FILE="$DOTFILES/setup/homebrew/Brewfile.$HOST"
export ZIM_HOME="$XDG_DATA_HOME/zim"
export HISTFILE="$XDG_STATE_HOME/zsh/history"
export LSCOLORS="Gxfxcxdxbxegedabagacad"
export LS_COLORS="di=1;36:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43"
export MAMBA_EXE="$HOMEBREW_PREFIX/bin/micromamba"
export MAMBA_ROOT_PREFIX="$XDG_DATA_HOME/micromamba"
