- name: Install terminal packages
  become: yes
  pacman:
    name:
      - base-devel
      - git

      - direnv
      - fish
      - starship

      - fd
      - ripgrep
      - ncdu
      - zoxide

      - vim
      - neovim
      - lazygit
      - prettier

      - xclip
      - xorg-xauth

      - openssh
      - networkmanager
      - nftables

      - less

      - zellij
      - openssh

      - podman
      - podman-compose
      - crun

      - bind
    state: present
    update_cache: yes

- name: Check if paru is already installed
  stat:
    path: /usr/bin/paru
  register: paru_installed

- name: Clone paru from AUR
  git:
    repo: "https://aur.archlinux.org/paru.git"
    dest: /tmp/paru
    update: yes
  when: not paru_installed.stat.exists

- name: Build and install paru
  command: makepkg -si --noconfirm
  args:
    chdir: /tmp/paru
    creates: /usr/bin/paru
  become: yes
  when: not paru_installed.stat.exists
