abbr --add --global python-dir 'echo "layout uv" > .envrc; direnv allow'
abbr --add --global python-uv-dir 'echo "layout python3" > .envrc; direnv allow'
abbr --add --global lazydots 'lazygit -p $DOTFILES'
abbr --add --global dots '$DOTFILES'
abbr --add --global dstow 'stow -d $DOTFILES -t $HOME --dotfiles'
abbr --add --global bw_session 'set -x BW_SESSION (bw unlock --raw)'
